steps:
  # build the container 
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/zingati-app/helloworld', '.']
    # Push the image to container registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/zingati-app/helloworld']
    # Deploy the container image to cloud run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'helloworld', '--image', 'gcr.io/zingati-app/helloword', '--region', 'us-east1', '--platform', 'managed', '--allow-unauthenticated']
# Redploy. Probably not a very good solution but this should work
images:
  - gcr.io/zingati-app/helloworld